### Global Findex Dataset Thailand EDA 
Thailand's Financial and Digital Financial Inclusion: A Comparative Analysis of Global Findex 2021 and 2024

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path

sns.set(style="whitegrid", context="notebook") 
plt.rcParams['figure.dpi'] = 100 
pd.set_option('display.max_columns', 12)
pd.set_option('display.max_rows', 12)

df1 = pd.read_csv(
    'Findex Raw data_2021 (0521-0223).csv',
    encoding='latin1'
)

df2 = pd.read_csv(
    'Findex Raw Data_2025 (0524-1224).csv',
    encoding='latin1'
)
print(df1.shape)
print(df2.shape)

(143887, 128)
(144090, 199)

In [2]:

print(df1['year'].value_counts())

year
2021    127854
2022     16033
Name: count, dtype: int64

In [3]:
df1.head()

,economy,economycode,regionwb,pop_adult,wpid_random,wgt,...,remittances,mobileowner,internetaccess,anydigpayment,merchantpay_dig,year
0,Afghanistan,AFG,South Asia,22647496.0,144274031,0.716416,...,5.0,1,2,1,0.0,2021
1,Afghanistan,AFG,South Asia,22647496.0,180724554,0.497408,...,5.0,1,2,0,0.0,2021
2,Afghanistan,AFG,South Asia,22647496.0,130686682,0.650431,...,3.0,2,2,0,0.0,2021
3,Afghanistan,AFG,South Asia,22647496.0,142646649,0.991862,...,5.0,1,2,0,0.0,2021
4,Afghanistan,AFG,South Asia,22647496.0,199055310,0.554940,...,5.0,2,2,0,0.0,2021

In [4]:
df2.head()

,year,economy,economycode,regionwb,pop_adult,wpid_random,...,fin49c,fin49d,fin49e,fin49f,fin50,fin51
0,2024,Nicaragua,NIC,Latin America & Caribbean (excluding high income),4830854,111111345,...,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,Costa Rica,CRI,Latin America & Caribbean (excluding high income),4118576,111111579,...,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,Mali,MLI,Sub-Saharan Africa (excluding high income),12725942,111112511,...,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,Kuwait,KWT,High income,3950546,111113432,...,NaN,NaN,NaN,NaN,1.0,1.0
4,2024,Turkiye,TUR,Europe & Central Asia (excluding high income),66691005,111115194,...,NaN,NaN,NaN,NaN,1.0,2.0

### EDA for Findex_dataset Thailand 2021 and 2024

In [5]:
print(df1.columns.to_list())
print(df2.columns.to_list())

['economy', 'economycode', 'regionwb', 'pop_adult', 'wpid_random', 'wgt', 'female', 'age', 'educ', 'inc_q', 'emp_in', 'urbanicity_f2f', 'account', 'account_fin', 'account_mob', 'fin1_1a', 'fin1_1b', 'fin2', 'fin4', 'fin4a', 'fin5', 'fin6', 'fin7', 'fin8', 'fin8a', 'fin8b', 'fin9', 'fin9a', 'fin10', 'fin10_1a', 'fin10_1b', 'fin10_1c', 'fin10_1d', 'fin10_1e', 'fin10a', 'fin10b', 'fin11_1', 'fin11a', 'fin11b', 'fin11c', 'fin11d', 'fin11e', 'fin11f', 'fin11g', 'fin11h', 'fin13_1a', 'fin13_1b', 'fin13_1c', 'fin13_1d', 'fin13_1e', 'fin13_1f', 'fin13a', 'fin13b', 'fin13c', 'fin13d', 'fin14_1', 'fin14_2', 'fin14_2_China', 'fin14a', 'fin14a1', 'fin14b', 'fin14c', 'fin14c_2', 'fin14c_2_China', 'fin16', 'fin17a', 'fin17a1', 'fin17b', 'fin20', 'fin22a', 'fin22b', 'fin22c', 'fin24', 'fin24a', 'fin24b', 'fin26', 'fin27_1', 'fin27c1', 'fin27c2', 'fin28', 'fin29_1', 'fin29c1', 'fin29c2', 'fin30', 'fin31a', 'fin31b', 'fin31b1', 'fin31b1_China', 'fin31c', 'fin32', 'fin33', 'fin34a', 'fin34b', 'fin34d', 'fin34e', 'fin35', 'fin37', 'fin38', 'fin39a', 'fin39b', 'fin39d', 'fin39e', 'fin42', 'fin42a', 'fin43a', 'fin43b', 'fin43d', 'fin43e', 'fin44a', 'fin44b', 'fin44c', 'fin44d', 'fin45', 'fin45_1', 'fin45_1_China', 'saved', 'borrowed', 'receive_wages', 'receive_transfers', 'receive_pension', 'receive_agriculture', 'pay_utilities', 'remittances', 'mobileowner', 'internetaccess', 'anydigpayment', 'merchantpay_dig', 'year']
['year', 'economy', 'economycode', 'regionwb', 'pop_adult', 'wpid_random', 'wgt', 'female', 'age', 'educ', 'inc_q', 'emp_in', 'urbanicity', 'account_fin', 'account_mob', 'account', 'dig_account', 'borrowed', 'saved', 'receive_wages', 'receive_transfers', 'receive_pensions', 'receive_agriculture', 'merchantpay_dig', 'pay_utilities', 'domestic_remittances', 'anydigpayment', 'fin2', 'fin3', 'fin4', 'fin5', 'fin6', 'fin7', 'fin8', 'fin9a', 'fin9b', 'fin10', 'fin11_0', 'fin11_1', 'fin11_2', 'fin11a', 'fin11b', 'fin11c', 'fin11d', 'fin11e', 'fin11f', 'fin13_1', 'fin13a', 'fin13b', 'fin13c', 'fin13d', 'fin13e', 'fin13f', 'fin13f_1', 'fin14a', 'fin14b', 'fin14c', 'fin14d', 'fin14e', 'fin15', 'fin16', 'fin17a', 'fin17b', 'fin17c', 'fin17d', 'fin17e', 'fin17f', 'fin18', 'fin19', 'fin20', 'fin21', 'fin22a', 'fin22a_1', 'fin22b', 'fin22c', 'fin22d', 'fin22e', 'fin22f', 'fin22g', 'fin22h', 'fin23', 'fin24', 'fin24a', 'fin24b', 'fin24c', 'fin24d1', 'fin24d2', 'fin24d3', 'fin25e1', 'fin25e2', 'fin25e3', 'fin25e4', 'fin26a', 'fin26b', 'fin27', 'fh1', 'fin28', 'fh2', 'fin29', 'fh2a', 'fin30', 'fin31a', 'fin31b', 'fin31c', 'fin31d', 'fin32', 'fin33', 'fin34a', 'fin34b', 'fin34c', 'fin34d', 'fin35', 'fin36', 'fin36a', 'fin37', 'fin38', 'fin39a', 'fin39b', 'fin39c', 'fin39d', 'fin40', 'fin41', 'fin41a', 'fin42', 'fin43a', 'fin43b', 'fin43c', 'fin43d', 'fin44', 'fin45', 'internet_use', 'con1', 'con2a', 'con2b', 'con2c', 'con2d', 'con2e', 'con2f', 'con2g', 'con3', 'con4', 'con5', 'con6', 'con7', 'con8', 'con9', 'con10', 'con11', 'con12', 'con13', 'con14', 'con15', 'con16', 'con17', 'con18', 'con19', 'con20', 'con21', 'con22', 'con23', 'con24', 'con25', 'con26', 'con27', 'con28', 'con29', 'con30a', 'con30b', 'con30c', 'con30d', 'con30e', 'con30f', 'con30g', 'con30h', 'con31a', 'con31b', 'con31c', 'con31d', 'con31e', 'con31f', 'con31g', 'con31h', 'con32', 'fin46', 'fin47', 'fin48a', 'fin48b', 'fin48c', 'fin48d', 'fin48e', 'fin48f', 'fin49a', 'fin49b', 'fin49c', 'fin49d', 'fin49e', 'fin49f', 'fin50', 'fin51']

In [6]:
# Select Thailand economic data from both datasets 
df1_thailand = df1[df1['economy'] == 'Thailand'].copy()
df2_thailand = df2[df2['economy'] == 'Thailand'].copy() 
print(df1_thailand.shape)
print(df2_thailand.shape)

(1017, 128)
(1000, 199)

In [7]:
print(df1_thailand['year'].value_counts())
print(df2_thailand['year'].value_counts())

year
2021    1017
Name: count, dtype: int64
year
2024    1000
Name: count, dtype: int64

In [8]:
print(set(df1_thailand.columns) - set(df2_thailand.columns))

{'fin44a', 'fin11g', 'fin45_1_China', 'fin8b', 'fin10_1c', 'internetaccess', 'fin10_1b', 'fin13_1b', 'fin29c1', 'fin8a', 'fin14c_2_China', 'fin13_1a', 'receive_pension', 'fin39e', 'fin17a1', 'fin29c2', 'fin10b', 'fin14_2_China', 'fin14a1', 'fin43e', 'fin11h', 'fin10a', 'fin44c', 'fin13_1c', 'fin27c2', 'fin1_1a', 'fin14c_2', 'fin13_1d', 'fin27_1', 'fin14_1', 'fin29_1', 'fin31b1', 'fin44d', 'fin10_1a', 'fin4a', 'fin27c1', 'fin9', 'fin26', 'fin34e', 'fin14_2', 'mobileowner', 'remittances', 'fin45_1', 'fin31b1_China', 'fin1_1b', 'fin13_1f', 'fin42a', 'urbanicity_f2f', 'fin10_1d', 'fin44b', 'fin13_1e', 'fin10_1e'}

In [9]:
print(set(df2_thailand.columns) - set(df1_thailand.columns))

{'con30b', 'con30d', 'fin17d', 'fin14e', 'fin51', 'con30g', 'fin18', 'fin22e', 'fin34c', 'fin19', 'con31e', 'fin21', 'fin49f', 'fin11_0', 'fin22h', 'con10', 'fin27', 'fin47', 'fin46', 'con30e', 'con32', 'con27', 'fin48a', 'con4', 'con2g', 'fin41a', 'fin49e', 'fin41', 'dig_account', 'con5', 'fin24c', 'fin25e2', 'con11', 'fin14d', 'fin36', 'fin36a', 'fin31d', 'con14', 'fin23', 'fin17c', 'con9', 'fin11_2', 'urbanicity', 'fin24d1', 'con21', 'con16', 'con18', 'con8', 'con2d', 'con29', 'fin49a', 'fin40', 'con30a', 'con30h', 'fin48d', 'fh2', 'con31a', 'fin22g', 'con22', 'con31d', 'con2e', 'fin24d2', 'fin48e', 'fin9b', 'fh2a', 'fin49b', 'fin13_1', 'fin22f', 'con2b', 'fin17e', 'fin3', 'con31g', 'internet_use', 'con20', 'fin13f_1', 'con17', 'fin24d3', 'fin25e3', 'fin29', 'domestic_remittances', 'fin22a_1', 'fin17f', 'fin13e', 'fh1', 'con31h', 'fin22d', 'fin49c', 'con24', 'con31c', 'con6', 'con2f', 'fin48c', 'con31b', 'fin15', 'con13', 'fin26b', 'con23', 'con2c', 'con28', 'con15', 'con30f', 'fin25e4', 'fin44', 'fin13f', 'fin25e1', 'con2a', 'con26', 'fin39c', 'fin26a', 'con1', 'receive_pensions', 'con3', 'fin43c', 'con31f', 'fin48b', 'fin48f', 'con7', 'fin50', 'fin49d', 'con25', 'con19', 'con30c', 'con12'}

### Variables exist in both datasets

In [10]:
common_columns = list(set(df1.columns) & set(df2.columns)) 
print(len(common_columns))
print(common_columns)

76
['merchantpay_dig', 'fin24a', 'fin9a', 'fin22c', 'borrowed', 'fin28', 'fin43b', 'fin24b', 'fin20', 'wpid_random', 'economycode', 'fin31a', 'fin6', 'fin37', 'economy', 'female', 'fin11f', 'fin11_1', 'saved', 'fin16', 'educ', 'fin45', 'fin43a', 'fin14c', 'fin30', 'age', 'fin4', 'wgt', 'fin31b', 'fin22a', 'receive_transfers', 'fin38', 'fin14b', 'fin17b', 'account_fin', 'fin11d', 'fin13c', 'fin5', 'fin35', 'fin13a', 'year', 'fin24', 'receive_agriculture', 'fin11b', 'fin34a', 'fin34d', 'regionwb', 'fin33', 'pop_adult', 'inc_q', 'fin32', 'fin39d', 'fin14a', 'anydigpayment', 'fin34b', 'fin7', 'fin22b', 'fin11a', 'fin11e', 'receive_wages', 'fin2', 'fin39b', 'fin43d', 'fin17a', 'fin11c', 'fin13b', 'emp_in', 'fin31c', 'fin42', 'account_mob', 'fin10', 'fin8', 'fin39a', 'account', 'fin13d', 'pay_utilities']

In [11]:
df_thai = pd.concat([df1_thailand, df2_thailand], ignore_index=True, sort=False)
print(df_thai.shape)
print(df_thai['year'].value_counts())

(2017, 251)
year
2021    1017
2024    1000
Name: count, dtype: int64

In [12]:
df_thai.head(10)

,economy,economycode,regionwb,pop_adult,wpid_random,wgt,...,fin49c,fin49d,fin49e,fin49f,fin50,fin51
0,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,156981272,0.224081,...,NaN,NaN,NaN,NaN,NaN,NaN
1,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,195399987,0.526118,...,NaN,NaN,NaN,NaN,NaN,NaN
2,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,181150505,0.148891,...,NaN,NaN,NaN,NaN,NaN,NaN
3,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,190062572,0.353825,...,NaN,NaN,NaN,NaN,NaN,NaN
4,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,146919431,0.138057,...,NaN,NaN,NaN,NaN,NaN,NaN
5,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,187160212,2.193632,...,NaN,NaN,NaN,NaN,NaN,NaN
6,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,124034566,2.320584,...,NaN,NaN,NaN,NaN,NaN,NaN
7,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,199028113,0.377784,...,NaN,NaN,NaN,NaN,NaN,NaN
8,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,121307534,1.251779,...,NaN,NaN,NaN,NaN,NaN,NaN
9,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,184101152,0.302764,...,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_common = df_thai[common_columns].copy()
print(df_common.shape)
print(df_common['year'].value_counts())

(2017, 76)
year
2021    1017
2024    1000
Name: count, dtype: int64

In [14]:
print(df_common.columns)

Index(['merchantpay_dig', 'fin24a', 'fin9a', 'fin22c', 'borrowed', 'fin28',
       'fin43b', 'fin24b', 'fin20', 'wpid_random', 'economycode', 'fin31a',
       'fin6', 'fin37', 'economy', 'female', 'fin11f', 'fin11_1', 'saved',
       'fin16', 'educ', 'fin45', 'fin43a', 'fin14c', 'fin30', 'age', 'fin4',
       'wgt', 'fin31b', 'fin22a', 'receive_transfers', 'fin38', 'fin14b',
       'fin17b', 'account_fin', 'fin11d', 'fin13c', 'fin5', 'fin35', 'fin13a',
       'year', 'fin24', 'receive_agriculture', 'fin11b', 'fin34a', 'fin34d',
       'regionwb', 'fin33', 'pop_adult', 'inc_q', 'fin32', 'fin39d', 'fin14a',
       'anydigpayment', 'fin34b', 'fin7', 'fin22b', 'fin11a', 'fin11e',
       'receive_wages', 'fin2', 'fin39b', 'fin43d', 'fin17a', 'fin11c',
       'fin13b', 'emp_in', 'fin31c', 'fin42', 'account_mob', 'fin10', 'fin8',
       'fin39a', 'account', 'fin13d', 'pay_utilities'],
      dtype='object')

### Renaming Columns

In [19]:
df_common_renamed = df_common.rename(columns={
        'merchantmerchantpay_dig': 'digital_merch_payment',
        'fin24a': 'emergency_fund_access',
        'fin9a':'received_acc_balance_info',
        'fin22c':'borrowed_from_savings_club',
        'borrowed':'borrowed_money',
        'fin28':'sent_domestic_remittance_account',
        'fin43b':'agri_payment_mobile',
        'fin24b':'emergency_fund_source',
        'fin20':'applied_for_mobile_loan',
        'wpid_random':'respondent_id',
        'fin31a':'utility_payment_bank',
        'fin6':'account_usage',
        'fin37':'received_goverment_transfer',
        'fin11f':'no_account_lack_of_trust',
        'fin11_1':'ever_had_bank_account',
        'saved':'saved_money',
        'fin16':'ever_had_mobile_money_account',
        'educ':'education_level',
        'fin45':'financial_health_indicator',
        'fin43a':'agri_payment_bank',
        'fin14c':'no_mobile_account_lack_documentation',
        'fin30':'made_utility_payment',
        'fin4':'debit_card_ownership',
        'wgt':'survey_weight',
        'fin31b':'utility_payment_mobile',
        'fin22a':'borrowed_from_formal_bank',
        'receive_transfers':'received_transfers',
        'fin38':'received_public_pension',
        'fin14b':'no_mobile_account_too_expensive',
        'fin17b':'saved_mobile_money',
        'account_fin':'financial_instituion_account',
        'fin11d':'no_account_insufficient_funds',
        'fin13c': 'mobile_money_usage',
        'fin5':'account_ownership', 'fin35':'high_withdrawal_fee_wages', 
        'fin13a':'mobile_money_activity',
        'year':'survey_year', 'fin24':'emergency_funds',
        'receive_agriculture':'received_agriculture_payment',
        'fin11b':'no_account_too_expensive',
        'fin34a':'wages_bank_account', 
        'fin34d':'wages_card',
        'regionwb':'world_bank_region',
        'fin33':'wage_payment_method',
        'pop_adult':'adult_population',
        'inc_q':'income_quintile',
        'fin32':'recieved_wages',
        'fin39d':'agriculture_payment_method',
        'fin14a':'no_mobile_agents_far',
        'anydigpayment':'any_digital_payment',
        'fin34b':'wages_mobile', 
        'fin7':'account_transaction_activity',
        'fin22b':'borrowed_from_family_friends',
        'fin11a':'no_account_distance',
        'fin11e':'no_account_family_member',
        'receive_wages':'received_wages',
        'fin2':'debit_card_ownership',
        'fin39b':'agricultural_payment_mobile',
        'fin43d':'agri_payment_card',
        'fin17a':'saved_bank',
        'fin11c':'no_account_documentation',
        'fin13b':'mobile_money_send_recieve',
        'emp_in':'employment_status',
        'fin31c':'utility_payment_cash',
        'fin42':'recieved_agricultural_payment',
        'account_mob':'mobile_money_account',
        'fin10':'credit_card_ownership',
        'fin8':'store_money_account',
        'fin39a':'agriculture_payment_account',
        'account':'account_ownership',
        'fin13d':'mobile_money_transaction',
        'pay_utilities':'utility_payment'})

In [23]:
# print(df_common_renamed.columns)
# df_common_renamed.head()
df_common_renamed.describe(include='all')

,merchantpay_dig,emergency_fund_access,received_acc_balance_info,borrowed_from_savings_club,borrowed_money,sent_domestic_remittance_account,...,credit_card_ownership,store_money_account,agriculture_payment_account,account_ownership,mobile_money_transaction,utility_payment
count,2017.000000,1733.000000,1744.000000,177.000000,2017.000000,1309.000000,...,1854.000000,1261.000000,1270.00000,2017.000000,422.000000,2017.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.607833,2.181766,1.506881,1.723164,0.540902,1.443850,...,1.484898,1.426646,1.28189,0.948438,1.132701,2.206743
std,0.488355,0.825315,0.602118,0.448704,0.498448,0.525441,...,0.530290,0.622632,0.46219,0.221195,0.366562,1.249363
min,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,1.000000,1.000000,1.00000,0.000000,1.000000,1.000000
25%,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000
50%,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,...,1.000000,1.000000,1.00000,1.000000,1.000000,2.000000
75%,1.000000,3.000000,2.000000,2.000000,1.000000,2.000000,...,2.000000,2.000000,2.00000,1.000000,1.000000,4.000000
max,1.000000,5.000000,4.000000,2.000000,1.000000,4.000000,...,4.000000,4.000000,4.00000,1.000000,3.000000,5.000000

### Demographic dataset

In [15]:
demo_cols = ['year','economy','economycode', 
            'wgt', 'female', 'age', 'educ',
            'inc_q', 'emp_in'] 

# Demographic columns for analysis 
demo_df = df_common[demo_cols].copy()
print(demo_df.head())
print(demo_df.shape)

   year   economy economycode       wgt  female   age  educ  inc_q  emp_in
0  2021  Thailand         THA  0.224081       1  27.0   3.0    4.0     1.0
1  2021  Thailand         THA  0.526118       2  30.0   3.0    4.0     1.0
2  2021  Thailand         THA  0.148891       1  45.0   3.0    4.0     1.0
3  2021  Thailand         THA  0.353825       1  45.0   3.0    1.0     1.0
4  2021  Thailand         THA  0.138057       2  39.0   3.0    4.0     1.0
(2017, 9)

In [16]:
# check NaN values
print(demo_df.isna().sum())

year            0
economy         0
economycode     0
wgt             0
female          0
age            10
educ            5
inc_q           0
emp_in          0
dtype: int64

In [28]:
print(demo_df.groupby('year')['age'].apply(lambda x: x.isna().sum()))
print(demo_df.groupby('year')['educ'].apply(lambda x: x.isna().sum()))
print(demo_df.groupby('year')['inc_q'].apply(lambda x: x.isna().sum()))
print(demo_df.groupby('year')['emp_in'].apply(lambda x: x.isna().sum()))

year
2021    10
2024     0
Name: age, dtype: int64
year
2021    0
2024    5
Name: educ, dtype: int64
year
2021    0
2024    0
Name: inc_q, dtype: int64
year
2021    0
2024    0
Name: emp_in, dtype: int64

In [17]:
# convert variables to nullable integers 
demo_df['age'] = demo_df['age'].astype('Int64')
demo_df['educ'] = demo_df['educ'].astype('Int64')

In [18]:
demo_df['year'] = demo_df['year'].astype('int64')
demo_df['female_binary'] = (demo_df['female'] == 1).astype('Int64') 
demo_df['inc_q'] = demo_df['inc_q'].astype('Int64')
demo_df['emp_in'] = demo_df['emp_in'].astype('Int64') 
print(demo_df.dtypes)
print(demo_df.head())

year               int64
economy           object
economycode       object
wgt              float64
female             int64
age                Int64
educ               Int64
inc_q              Int64
emp_in             Int64
female_binary      Int64
dtype: object
   year   economy economycode       wgt  female  age  educ  inc_q  emp_in  \
0  2021  Thailand         THA  0.224081       1   27     3      4       1
1  2021  Thailand         THA  0.526118       2   30     3      4       1
2  2021  Thailand         THA  0.148891       1   45     3      4       1
3  2021  Thailand         THA  0.353825       1   45     3      1       1
4  2021  Thailand         THA  0.138057       2   39     3      4       1

   female_binary
0              1
1              0
2              1
3              1
4              0

### Financial inclusion Dataset

In [ ]:
### Financial inclusion Dataset

finance_df = df_common[]